name = "rutinko-push"
main = "worker/src/index.js"
compatibility_date = "2026-07-06"
workers_dev = true

[vars]
ALLOWED_ORIGIN = "*"
PUSH_TTL_SECONDS = "1800"
PUSH_URGENCY = "normal"
VAPID_PUBLIC_KEY = "BIDkEP4o7yj5bqTPYOTEbgljyCx_9YuWfg3SSnGD7DQ3EQN_wtfi73RkiSJ4ByCB_dzo-n3wmQmftBWa1wZ_KyI"
VAPID_SUBJECT = "mailto:ig29007@gmail.com"

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "RUTINKO_PUSH_KV"
id = "0393976ea08147a08cdeecdae27d1738"
